#!/usr/bin/env python3
"""
Enrich Products Script

This script takes a JSON file with partial product data and uses ChatGPT
to generate the missing fields needed for the gift recommendation database.

Input JSON format:
[
  {
    "name": "Product Name",
    "amazon_url": "https://amzn.to/xxxxx",
    "price": 49.99,
    "prime_eligible": true,
    "image_url": "https://...",
    "product_description": "The actual Amazon listing description..."
  }
]

Output: Complete JSON ready for bulk import with add_product.py

Usage:
    python scripts/enrich_products.py input.json output.json
    python scripts/enrich_products.py input.json  # outputs to input_enriched.json
"""

import os
import sys
import json
import argparse
from typing import Optional
from dataclasses import dataclass, asdict
from dotenv import load_dotenv
from openai import OpenAI

# Load environment variables
load_dotenv()

# ============================================================================
# CONFIGURATION
# ============================================================================

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

if not OPENAI_API_KEY:
    print("❌ Missing OPENAI_API_KEY environment variable!")
    print("   Please set it in your .env file.")
    sys.exit(1)

openai_client = OpenAI(api_key=OPENAI_API_KEY)

# ============================================================================
# TYPES
# ============================================================================

@dataclass
class PartialProduct:
    """Input product with only basic info"""
    name: str
    amazon_url: str
    price: float
    prime_eligible: bool
    product_description: str  # The actual Amazon listing description
    image_url: Optional[str] = None


@dataclass
class GeneratedFields:
    """Fields generated by ChatGPT"""
    min_age: int
    max_age: int
    gender: str
    category: str
    description: str
    tags: list[str]


@dataclass
class CompleteProduct:
    """Complete product ready for database import"""
    name: str
    amazon_url: str
    price: float
    prime_eligible: bool
    product_description: str  # The actual Amazon listing description
    image_url: Optional[str]
    min_age: int
    max_age: int
    gender: str
    category: str
    description: str  # AI-generated semantic description for matching
    tags: list[str]


# ============================================================================
# CHATGPT ENRICHMENT
# ============================================================================

SYSTEM_PROMPT = """You are a helpful assistant that analyzes products for a Christmas gift recommendation website.

Given a product name, price, and the Amazon listing description, generate the following attributes:

1. min_age: Minimum recommended age (integer, 0-99)
2. max_age: Maximum recommended age (integer, 0-99)
3. gender: Who this gift is best for ("male", "female", or "unisex")
4. category: Product category (e.g., "electronics", "toys", "books", "home", "fashion", "sports", "beauty", "games", "kitchen", "outdoor")
5. description: 1-3 sentences describing who this gift is PERFECT for. Focus on personality traits, interests, and hobbies. This will be used for AI semantic matching, so be descriptive about the TYPE of person who would love this gift.
6. tags: Array of 3-7 keywords/phrases that describe the ideal recipient (e.g., ["tech lover", "gamer", "outdoorsy", "minimalist"])

Respond ONLY with valid JSON matching this exact structure:
{
  "min_age": 13,
  "max_age": 99,
  "gender": "unisex",
  "category": "electronics",
  "description": "Perfect for tech enthusiasts who love smart home gadgets...",
  "tags": ["tech lover", "smart home", "gadgets"]
}"""


def enrich_product(product: PartialProduct) -> GeneratedFields:
    """Use ChatGPT to generate missing product fields"""

    user_prompt = f"""Product: {product.name}
Price: ${product.price}
Prime Eligible: {"Yes" if product.prime_eligible else "No"}

Amazon Listing Description:
{product.product_description}

Based on this product information, generate the gift recommendation attributes."""

    response = openai_client.chat.completions.create(
        model="gpt-4o-mini",  # Fast and cheap, good for this task
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt}
        ],
        response_format={"type": "json_object"},
        temperature=0.7,
    )

    # Parse the JSON response
    result = json.loads(response.choices[0].message.content)

    return GeneratedFields(
        min_age=result["min_age"],
        max_age=result["max_age"],
        gender=result["gender"],
        category=result["category"],
        description=result["description"],
        tags=result["tags"],
    )


def merge_product(partial: PartialProduct, generated: GeneratedFields) -> CompleteProduct:
    """Combine partial product data with generated fields"""
    return CompleteProduct(
        name=partial.name,
        amazon_url=partial.amazon_url,
        price=partial.price,
        prime_eligible=partial.prime_eligible,
        product_description=partial.product_description,
        image_url=partial.image_url,
        min_age=generated.min_age,
        max_age=generated.max_age,
        gender=generated.gender,
        category=generated.category,
        description=generated.description,
        tags=generated.tags,
    )


# ============================================================================
# MAIN PROCESSING
# ============================================================================

def process_products(input_path: str, output_path: str) -> None:
    """Process all products in the input file"""

    # Read input file
    if not os.path.exists(input_path):
        print(f"❌ File not found: {input_path}")
        sys.exit(1)

    with open(input_path, "r") as f:
        raw_products = json.load(f)

    if not isinstance(raw_products, list):
        print("❌ Input JSON must be an array of products")
        sys.exit(1)

    print(f"🎄 Enriching {len(raw_products)} products...\n")

    complete_products = []
    success_count = 0
    error_count = 0

    for i, raw in enumerate(raw_products, 1):
        try:
            # Parse partial product
            partial = PartialProduct(
                name=raw["name"],
                amazon_url=raw["amazon_url"],
                price=raw["price"],
                prime_eligible=raw.get("prime_eligible", False),
                product_description=raw["product_description"],
                image_url=raw.get("image_url"),
            )

            print(f"[{i}/{len(raw_products)}] 🎁 {partial.name}")
            print(f"         💰 ${partial.price}")

            # Generate missing fields with ChatGPT
            print(f"         🤖 Generating attributes...")
            generated = enrich_product(partial)

            print(f"         📦 Category: {generated.category}")
            print(f"         👤 Age: {generated.min_age}-{generated.max_age}, Gender: {generated.gender}")
            print(f"         🏷️  Tags: {', '.join(generated.tags[:3])}...")

            # Merge into complete product
            complete = merge_product(partial, generated)
            complete_products.append(asdict(complete))

            print(f"         ✅ Done\n")
            success_count += 1

        except KeyError as e:
            print(f"         ❌ Missing required field: {e}\n")
            error_count += 1
        except Exception as e:
            print(f"         ❌ Error: {e}\n")
            error_count += 1

    # Write output file
    with open(output_path, "w") as f:
        json.dump(complete_products, f, indent=2)

    print("═" * 50)
    print(f"✅ Complete: {success_count} enriched, {error_count} failed")
    print(f"📁 Output saved to: {output_path}")
    print("")
    print("Next step: Run the bulk import:")
    print(f"  python scripts/add_product.py --bulk {output_path}")


# ============================================================================
# CLI
# ============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Enrich partial product data with AI-generated attributes"
    )
    parser.add_argument(
        "input",
        help="Input JSON file with partial product data"
    )
    parser.add_argument(
        "output",
        nargs="?",
        help="Output JSON file (default: input_enriched.json)"
    )

    args = parser.parse_args()

    # Generate default output path if not provided
    if args.output:
        output_path = args.output
    else:
        base = os.path.splitext(args.input)[0]
        output_path = f"{base}_enriched.json"

    process_products(args.input, output_path)


if __name__ == "__main__":
    main()
